language: java
jdk:
  - oraclejdk8
before_install:
- if [ $TRAVIS_PULL_REQUEST = "false" && $TRAVIS_BRANCH = "master" ]; then
    openssl aes-256-cbc -K $encrypted_133b6038fc3e_key -iv $encrypted_133b6038fc3e_iv -in maven_files.tar.enc -out maven_files.tar -d;
    tar xvf maven_files.tar;
    mv settings.xml ~/.m2/settings.xml;
    gpg --import travis.gpg;
  fi
after_success:
- if [ $TRAVIS_PULL_REQUEST = "false" && $TRAVIS_BRANCH = "master" ]; then
    mvn deploy;
  fi
- ! '[[ $TRAVIS_TAG == xtrest-[0-9.]* ]] && mvn clean deploy -Prelease'
